import React from 'react';
import { useGetExchangesQuery } from '../../services/cryptoApi';
import HTMLReactParser from 'html-react-parser';
import millify from 'millify';
import Spinner from '../Spinner';
import { Button, Menu, Collapse, Row, Col, Typography, Avatar } from 'antd';

const { Text } = Typography;
const { Panel } = Collapse;

const data = {
  status: 'success',
  data: {
    stats: { volume: 161218902301.01782, total: 373, limit: 50, offset: 0 },
    currencies: [
      {
        id: 1509,
        uuid: 'yhjMzLPhuIDl',
        type: 'fiat',
        iconUrl: 'https://cdn.coinranking.com/kz6a7w6vF/usd.svg',
        name: 'US Dollar',
        symbol: 'USD',
        sign: '$',
      },
    ],
    exchanges: [
      {
        id: 286,
        uuid: '-zdvbieRdZ',
        name: 'Binance',
        description:
          '<p><a href="https://www.binance.com/en/register?ref=35424440" rel="nofollow noopener" target="_blank">Binance</a> is a blockchain ecosystem comprising a cryptocurrency exchange, startup incubator, startup investor, and coin information provider. <a href="http://www.binance.com/en/register?ref=35424440" rel="nofollow noopener" target="_blank">Binance</a> is a highly popular exchange and allows its users to trade hundreds of cryptocurrencies, including Dogecoin, Bitcoin, and Ethereum.</p>\n\n<p>The exchange was founded in July 2017, by Changpeng Zhao (CZ), and was initially based in China, but was later moved out of China due to China&#39;s increasing regulation of cryptocurrency. The name &lsquo;Binance&rsquo; comes from the two words &lsquo;binary&rsquo; and &lsquo;finance&rsquo;.&nbsp;<a href="https://www.binance.com/en/register?ref=35424440" rel="nofollow noopener" target="_blank">Binance exchange</a> requires KYC (know-your-customer), which is the process that banks gather identifying data and contact information from current and potential customers, to prevent fraud. <a href="http://www.binance.com/en/register?ref=35424440" rel="nofollow noopener" target="_blank">Binance</a> is capable of processing 1,400,000 orders per second and supports many cryptocurrencies. Binance serves more than 15,000,000 users worldwide, operates in over 40 countries, and is based in over 180 countries &amp; regions.</p>\n\n<h3>Binance coin (BNB)</h3>\n\n<p><a href="https://coinranking.com/coin/WcwrkfNI4FUAe+binancecoin-bnb" rel="nofollow noopener" target="_blank">Binance coin (BNB)</a>&nbsp;is the native asset on Binance Chain and powers the Binance ecosystem. BNB has several use cases, like fueling transactions on the chain, paying for transaction fees on <a href="https://www.binance.com/en/register?ref=35424440" rel="nofollow noopener" target="_blank">Binance Exchange</a>, and making in-store payments.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/mDTK5qrmq/binance.svg',
        verified: false,
        lastTickerCreatedAt: 1636633694000,
        numberOfMarkets: 1269,
        volume: 49018484786.54262,
        websiteUrl: 'https://www.binance.com/en/register?ref=35424440',
        rank: 1,
        marketShare: 30.404924042354768,
      },
      {
        id: 287,
        uuid: 'hUlMcwWZp_',
        name: 'OKEx',
        description:
          '<p><a href="https://www.okex.com/join/7603209" rel="nofollow noopener" target="_blank">OKEx</a> is a global bitcoin exchange that claims to be secured with bank-level SSL encryption and cold storage. This exchange provides more than four hundred tokens &amp; futures trading pairs enabling users to optimize their strategy. OKEx wants to provide a safe, reliable, and stable environment for digital asset trading. They serve customers from over a hundred countries.</p>\n\n<h3>OKEx security</h3>\n\n<p><a href="https://www.okex.com/join/7603209" rel="nofollow noopener" target="_blank">OKEx</a> has a big focus on security. They aim to provide a safe, reliable, and stable environment for digital assets trading. The exchange uses KYC (know-your-customer); users must complete at least KYC verification level 1 in order to withdraw tokens from OKEx.</p>\n\n<h3>OKEx specialties</h3>\n\n<p><a href="https://www.okex.com/join/7603209" rel="nofollow noopener" target="_blank">OKEx</a> believes blockchain technology will eliminate barriers to transactions, increase the efficiency of transactions across society, and eventually have a significant impact on the global economy. The exchange strives to achieve something that changes the world and never stops to innovate and improve our customer experience.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/tBA4j321g/Okex.svg',
        verified: false,
        lastTickerCreatedAt: 1636633702000,
        numberOfMarkets: 473,
        volume: 12733489064.053514,
        websiteUrl: 'https://www.okex.com/join/7603209',
        rank: 2,
        marketShare: 7.898260614799586,
      },
      {
        id: 336,
        uuid: 'xRvYoPjeQ',
        name: 'Huobi Global',
        description:
          '<p>&nbsp;</p>\n\n<p><a href="https://www.huobi.com/en-us/topic/invited/?invite_code=58q3b" rel="nofollow noopener" target="_blank">Huobi&nbsp;Global</a> is a cryptocurrency exchange headquartered&nbsp;in&nbsp;Beijing and with offices in Chengdu, Hong Kong, Seoul, Shenzhen, Singapore, and Tokyo. The exchange was founded in September 2013 and is one of the largest digital currency exchanges in China. The platform features a distributed system architecture built to protect against DDoS and other potential threats. The app is available for&nbsp;iOS&nbsp;and Android.&nbsp;<a href="http://www.huobi.com/en-us/topic/invited/?invite_code=58q3b" rel="nofollow noopener" target="_blank">Huobi Global</a> says to be&nbsp;devoted to providing secure and reliable digital asset trading and asset management services to global users.</p>\n\n<p><a href="http://www.huobi.com/en-us/topic/invited/?invite_code=58q3b" rel="nofollow noopener" target="_blank">Huobi Global</a> allows users to exchange crypto for crypto, including Bitcoin, USDT, and Ethereum. Currently, they have almost 300 cryptocurrencies available and support nearly 800 trading pairs.</p>\n\n<h2>Huobi Token (HT)</h2>\n\n<p><a href="https://coinranking.com/coin/DXwP4wF9ksbBO+huobitoken-ht" rel="nofollow noopener" target="_blank">Huobi Token (HT)</a>&nbsp;is the exchange-based and native token of <a href="http://www.huobi.com/en-us/topic/invited/?invite_code=58q3b" rel="nofollow noopener" target="_blank">Huobi Global</a>.&nbsp;It can be used to purchase monthly VIP status plans for transaction fee discounts, receive crypto rewards from seasonal buybacks, vote on exchange decisions, and gain early access to special Huobi events.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/ryFpQe0c7/ht.svg',
        verified: false,
        lastTickerCreatedAt: 1636633737000,
        numberOfMarkets: 839,
        volume: 8252818025.532341,
        websiteUrl:
          'https://www.huobi.com/en-us/topic/invited/?invite_code=58q3b',
        rank: 3,
        marketShare: 5.119013904537817,
      },
      {
        id: 337,
        uuid: 'fCE_BnQ7C',
        name: 'ZB Global',
        description:
          '<p><a href="https://www.zbg.com/newEn?recommendCode=ODV5d09XYmJCbUM=" rel="nofollow noopener" target="_blank">ZBG</a> is a global centralized cryptocurrency exchange with its headquarters in Hong Kong, launched in July 2018. It is actually a subsidiary of another older, larger, and well-established exchange ZB.COM.&nbsp;Currently, ZBG supports 11 languages and provides services for 3 million users around the world with trustworthy cryptocurrency spot and derivatives trading, and other crypto asset investment services. ZBG&rsquo;s mobile app is available for iOS and Android.</p>\n\n<h2>ZBG native token</h2>\n\n<p>ZBG Token (ZT) is an exchange based token and native currency of the <a href="https://www.zbg.com/newEn?recommendCode=ODV5d09XYmJCbUM=" rel="nofollow noopener" target="_blank">ZBG crypto exchange</a>. The ZT can be used to purchase monthly VIP status plans for transaction fee discounts, vote on exchange decisions, gain early access to special ZBG launchpad events, and trade with other cryptocurrencies listed on the ZBG exchange.</p>\n\n<h2>ZBG security</h2>\n\n<p>As safety is the key point in cryptocurrency trading, <a href="https://www.zbg.com/newEn?recommendCode=ODV5d09XYmJCbUM=" rel="nofollow noopener" target="_blank">ZBG</a> uses multiple technologies to protect its users and assets. SMS authorization, e-mail binding, two-factor authentication with Time-based One-time Password Algorithm and HMAC-based One-time Password Algorithm from Google, and storing 95% of digital assets in cold wallets help to provide a high level of security.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/QlCcXk0P5/zbg.svg',
        verified: false,
        lastTickerCreatedAt: 1636633736000,
        numberOfMarkets: 60,
        volume: 4732046840.6715145,
        websiteUrl: 'https://www.zbg.com/newEn?recommendCode=ODV5d09XYmJCbUM=',
        rank: 5,
        marketShare: 2.935168750768525,
      },
      {
        id: 280,
        uuid: 'YBU1UXLeVc9D',
        name: 'Bitrue',
        description:
          '<p><a href="https://www.bitrue.com/activity/task/task-landing?inviteCode=EATETZE&amp;cn=900000" rel="nofollow noopener" target="_blank">Bitrue</a> is a cryptocurrency exchange based in Singapore. The platform was launched in 2018 by a group of blockchain enthusiasts. Apart from spot trading, <a href="https://www.bitrue.com/activity/task/task-landing?inviteCode=EATETZE&amp;cn=900000" rel="nofollow noopener" target="_blank">Bitrue</a> has also launched an &ldquo;interest-earn program&rdquo;, supporting over ten cryptocurrencies. They have an annual percentage rate of up to 15%. Bitrue also launched crypto-backed loan services.</p>\n\n<p><a href="https://www.bitrue.com/activity/task/task-landing?inviteCode=EATETZE&amp;cn=900000" rel="nofollow noopener" target="_blank">Bitrue</a> claims to be dedicated &ldquo;to providing a safe and convenient service for cryptocurrency trading, and being the best aggregator of qualified cryptocurrency all over the world.&rdquo; The cryptocurrency exchange focuses on being safer, faster, and easier. They offer two-factor authentication, multi-signature, and have a cold wallet.</p>\n\n<h2>Bitrue Coin (BTR)</h2>\n\n<p><a href="https://coinranking.com/coin/SLYjzF4ty+bitruecoin-btr" rel="nofollow noopener" target="_blank">Bitrue Coin (BTR)</a> is the native asset on the Bitrue exchange. This coin is created to support and involve all Bitrue users with trading fee deductions, cash deposits by projects, voting for listings, wealth management programs, and loan programs.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/Qixby2IZc/Bitrue.svg',
        verified: false,
        lastTickerCreatedAt: 1636633698000,
        numberOfMarkets: 313,
        volume: 4679634613.6324215,
        websiteUrl:
          'https://www.bitrue.com/activity/task/task-landing?inviteCode=EATETZE&cn=900000',
        rank: 6,
        marketShare: 2.90265877440035,
      },
      {
        id: 341,
        uuid: '-4x6SL_Cv',
        name: 'Kucoin',
        description:
          '<p><a href="https://www.kucoin.com/ucenter/signup?rcode=1s6g2eR" rel="nofollow noopener" target="_blank">KuCoin</a>&nbsp;is a crypto exchange that allows you to buy, sell and trade cryptocurrencies. The platform is also known as &quot;The People&#39;s Exchange&quot;, and is headquartered in Singapore. It was officially launched in May 2017, founded by a group of experienced business specialists in 2013; Michael Gan, Eric Don, Top Lan, Kent Li, John Lee, Jack Zhu, and Linda Lin.&nbsp;</p>\n\n<p>The founders wanted to create a simple and safe platform for people all over the world to use&nbsp;<a href="https://www.kucoin.com/ucenter/signup?rcode=1s6g2eR" rel="nofollow noopener" target="_blank">to trade a range of digital coins</a>. KuCoin aims to find the best available crypto projects to list on their platform. <a href="http://www.kucoin.com/ucenter/signup?rcode=1s6g2eR" rel="nofollow noopener" target="_blank">KuCoin</a> is accessible through the KuCoin app (Android and iOS) and through their website.&nbsp;<a href="http://www.kucoin.com/ucenter/signup?rcode=1s6g2eR" rel="nofollow noopener" target="_blank">KuCoin</a> has more than 600 different trading pairs available. They support over 300 cryptocurrencies, including the most well-known coins like Bitcoin, Ethereum, and Dogecoin. KuCoin is also known for adding coins that just have completed their ICO.&nbsp;This means you can follow these cryptocurrencies from the beginning.</p>\n\n<h2>KuCoin token (KCS)</h2>\n\n<p><a href="https://coinranking.com/coin/LOO6LmXd7G84Z+kucointoken-kcs" rel="nofollow noopener" target="_blank">KuCoin Token (KCS)</a> is the native token of KuCoin. Its initial supply was set at 200 million, with a monthly burning system that will continue until just 100 million KCS remain. KuCoin token allows traders to benefit from the growth that occurs within the exchange. They originally started as ERC-20 tokens that ran on the Ethereum blockchain, but this is more likely to change moving forward.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/A-hAjR-hN/kucoin.png',
        verified: false,
        lastTickerCreatedAt: 1636633461000,
        numberOfMarkets: 750,
        volume: 4666667839.561859,
        websiteUrl: 'https://www.kucoin.com/ucenter/signup?rcode=1s6g2eR',
        rank: 7,
        marketShare: 2.89461581300718,
      },
      {
        id: 516,
        uuid: '_qq3t0X7Q',
        name: 'FTX',
        description:
          '<p>&nbsp;</p>\n\n<p><a href="https://ftx.com/#a=22821485" rel="nofollow noopener" target="_blank">FTX</a> is a cryptocurrency derivatives exchange, aiming to build a platform powerful enough for professional trading firms and intuitive enough for first-time users. FTX is backed by Alameda Research, a cryptocurrency liquidity provider.<a href="http://www.kucoin.com/ucenter/signup?rcode=1s6g2eR" rel="nofollow noopener" target="_blank"> Binance</a>, a leading cryptocurrency exchange, invested in FTX in December 2019.&nbsp;</p>\n\n<p>The creators of FTX said they founded this platform out of frustrations towards other cryptocurrency exchanges. FTX aims to tackle issues regarding clawbacks, broken liquidation Systems, poorly designed products and margin wallets. The mission of the FTX team is &ldquo;to build the best derivatives exchange and to help move the crypto space toward becoming institutional.&rdquo;</p>\n\n<h2>FTX Token (FTT)</h2>\n\n<p><a href="https://coinranking.com/coin/NfeOYfNcl+ftxtoken-ftt" rel="nofollow noopener" target="_blank">FTX Token (FTT)</a> is the native token of <a href="https://ftx.com/#a=22821485" rel="nofollow noopener" target="_blank">FTX Exchange</a>. As a holder of this token, you&nbsp;pay fewer FTX trading fees,&nbsp;receive socialized gains from the insurance fund, you can buy and burn the fees weekly, and&nbsp;use it as collateral for futures trading.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/Np95rtMR2/ftx-exchange.svg',
        verified: false,
        lastTickerCreatedAt: 1636633565000,
        numberOfMarkets: 200,
        volume: 4522236670.019266,
        websiteUrl: 'https://ftx.com/#a=22821485',
        rank: 8,
        marketShare: 2.805028818255833,
      },
      {
        id: 590,
        uuid: '84SYQYPi5D',
        name: 'Crypto.com',
        description:
          '<p><a href="https://www.dpbolvw.net/click-100410788-14481994?sid=5813542" rel="nofollow noopener" target="_blank">Crypto.com</a> is a cryptocurrency exchange. Their mission is to accelerate the world&#39;s transition to cryptocurrency.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/NyAQsixIU/crypto-com.svg',
        verified: false,
        lastTickerCreatedAt: 1636633638000,
        numberOfMarkets: 224,
        volume: 4405438607.173555,
        websiteUrl:
          'https://www.dpbolvw.net/click-100410788-14481994?sid=5813542',
        rank: 9,
        marketShare: 2.7325819393981465,
      },
      {
        id: 331,
        uuid: 'qwNm71bvH',
        name: 'HitBTC',
        description:
          'HitBTC is an exchange that opened its doors in 2013 and offers many trading markets for a variety of coins.',
        iconUrl: 'https://cdn.coinranking.com/ryj4MjHCQ/hitbtc.svg',
        verified: false,
        lastTickerCreatedAt: 1636633736000,
        numberOfMarkets: 1091,
        volume: 3852875260.8679037,
        websiteUrl: 'https://www.hitbtc.com',
        rank: 10,
        marketShare: 2.389840896989893,
      },
      {
        id: 479,
        uuid: 'APhqviEvm',
        name: 'INDOEX',
        description: null,
        iconUrl: 'https://cdn.coinranking.com/IHyYq38Jm/INDOEX.svg',
        verified: false,
        lastTickerCreatedAt: 1636633549000,
        numberOfMarkets: 170,
        volume: 3617757601.6202245,
        websiteUrl: 'https://international.indoex.io/',
        rank: 11,
        marketShare: 2.2440033705634432,
      },
      {
        id: 613,
        uuid: 'LtNqM79f9R',
        name: 'Changelly PRO',
        description:
          '<p><a href="https://pro.changelly.com/referral/db74a1126d99d1c9" rel="nofollow noopener" target="_blank">Changelly PRO</a> was launched on the sixth of July 2020 and is another version of Changelly. Changelly PRO has spot and margin trading OTC, but will also have fiat on-ramp in the future.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/AvbhQzPFY/changelly-pro.png',
        verified: false,
        lastTickerCreatedAt: 1636633653000,
        numberOfMarkets: 123,
        volume: 3315355283.2636156,
        websiteUrl: 'https://pro.changelly.com/referral/db74a1126d99d1c9',
        rank: 12,
        marketShare: 2.05643087500583,
      },
      {
        id: 321,
        uuid: '2Vu9j1PmUbx',
        name: 'Kraken',
        description:
          '<p><a href="https://r.kraken.com/EaEvkQ" rel="nofollow noopener" target="_blank">Kraken</a> is a global cryptocurrency exchange based in San Francisco. Founded in 2011, Kraken is one of the oldest (bitcoin) exchanges.&nbsp;<a href="https://r.kraken.com/EaEvkQ" rel="nofollow noopener" target="_blank">Kraken</a> wants to make&nbsp;cryptocurrency available and accessible to the world and enabling people from all walks of life to invest in their independence.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/jqjP32iqz/kraken.svg',
        verified: false,
        lastTickerCreatedAt: 1636633723000,
        numberOfMarkets: 380,
        volume: 2964259374.7253165,
        websiteUrl: 'https://r.kraken.com/EaEvkQ',
        rank: 13,
        marketShare: 1.8386549792968059,
      },
      {
        id: 346,
        uuid: 'WmdeT9i2q',
        name: 'Bitfinex',
        description:
          '<p><a href="https://bitfinex.com/?refcode=UbLuXyT0K" rel="nofollow noopener" target="_blank">Bitfinex</a> is a spot trading platform for all major digital assets and cryptocurrencies. The crypto exchange was founded in 2012 and is Hong Kong-based. <a href="https://bitfinex.com/?refcode=UbLuXyT0K" rel="nofollow noopener" target="_blank">Bitfinex</a> is owned and operated by iFinex Inc, which is headquartered in Hong Kong and registered in the British Virgin Islands.</p>\n\n<p><a href="https://bitfinex.com/?refcode=UbLuXyT0K" rel="nofollow noopener" target="_blank">Bitfinex</a>&#39;s mission is to give its users the ultimate cryptocurrency trading experience. The team strives to achieve it by providing its users with state-of-the-art trading tools, innovative technology, and unparalleled levels of customer service.</p>\n\n<p>In addition to a suite of advanced trading features and charting tools, <a href="https://bitfinex.com/?refcode=UbLuXyT0K" rel="nofollow noopener" target="_blank">Bitfinex</a> provides access to peer-to-peer (P2P) financing, an OTC market, and margin trading for a wide selection of digital assets and derivatives trading. Bitfinex&rsquo;s strategy focuses on delivering the best crypto trading experience for professional traders and liquidity providers around the world through the delivery of cutting-edge technology.</p>\n\n<h2>Leo Token (LEO)</h2>\n\n<p>LEO (LEO) is the utility token issued by parent company iFinex. The token is intended for use on the <a href="https://bitfinex.com/?refcode=UbLuXyT0K" rel="nofollow noopener" target="_blank">Bitfinex exchange</a> and other trading platforms managed by iFinex. The token aims to strengthen the Bitfinex community and optimize the platform&rsquo;s operations.</p>\n\n<p>&nbsp;</p>\n',
        iconUrl: 'https://cdn.coinranking.com/VSt4Or6D6/Bitfinex.svg',
        verified: false,
        lastTickerCreatedAt: 1636633461000,
        numberOfMarkets: 418,
        volume: 2843613801.8041883,
        websiteUrl: 'https://bitfinex.com/?refcode=UbLuXyT0K',
        rank: 14,
        marketShare: 1.763821587430716,
      },
      {
        id: 343,
        uuid: '5-CEoAKXc',
        name: 'P2PB2B',
        description: null,
        iconUrl: 'https://cdn.coinranking.com/oMYGUH2Ok/p2pb2b.svg',
        verified: false,
        lastTickerCreatedAt: 1636633461000,
        numberOfMarkets: 211,
        volume: 2507961157.581994,
        websiteUrl: 'https://p2pb2b.io',
        rank: 15,
        marketShare: 1.5556247572628217,
      },
      {
        id: 301,
        uuid: 'XHp8eCjIDc',
        name: 'ZB',
        description: null,
        iconUrl: 'https://cdn.coinranking.com/VhtrNhSv7/ZB.svg',
        verified: false,
        lastTickerCreatedAt: 1636633711000,
        numberOfMarkets: 134,
        volume: 2407613165.191777,
        websiteUrl: 'https://www.zbex.club/en/register?ref=1475qtlg',
        rank: 17,
        marketShare: 1.4933814402832446,
      },
      {
        id: 353,
        uuid: 'Z7wAB_T0o',
        name: 'Coinsbit',
        description:
          '<p><strong>We have received several reports about this exchange. Therefore, be careful and always do your research!</strong></p>\n',
        iconUrl: 'https://cdn.coinranking.com/Xx7PRnP31/coinsbit.svg',
        verified: false,
        lastTickerCreatedAt: 1636633461000,
        numberOfMarkets: 183,
        volume: 2124203584.536848,
        websiteUrl: 'https://coinsbit.io/',
        rank: 18,
        marketShare: 1.3175896586683542,
      },
      {
        id: 339,
        uuid: 'h0n6yGf3J',
        name: 'Gate.io',
        description:
          '<p>&nbsp;</p>\n\n<p><a href="https://www.gate.io/signup/4296215" rel="nofollow noopener" target="_blank">Gate.io</a> is a cryptocurrency exchange platform that started in 2017. <a href="http://www.gate.io/signup/4296215" rel="nofollow noopener" target="_blank">Gate.io</a> was first founded in 2013 under the name Bter.com by CEO Lin Han. In 2017 it was rebranded to Gate.io. The exchange was known as a Chinese platform, but right now it is not associated with China and seems to be US-based with a registered address in Virginia. Gate.io supports 400 cryptocurrencies and has almost 800 trading pairs available.</p>\n\n<p>Gate.io aims to protect its users&#39; funds with both centralized and decentralized methods. The exchange claims to have invested millions in security and law funds to add extra protection for the users&rsquo; assets.</p>\n\n<h2><strong>GateToken (GT)</strong></h2>\n\n<p><a href="https://coinranking.com/coin/t7m8DZVyMsAu+gatetoken-gt" rel="nofollow noopener" target="_blank">GateToken (GT)</a> is the native token of the Gatechain mainnet. It became the exchange token of<a href="https://www.gate.io/signup/4296215" rel="nofollow noopener" target="_blank"> Gate.io</a> in 2020. GateToken can be used in VIP tier escalation, trading fee debit, exclusive activities participation, and more. <a href="http://www.gate.io/signup/4296215" rel="nofollow noopener" target="_blank">Gate.io</a> stated to increasingly empower GT with more and more applications and use cases to improve its intrinsic value.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/9TO47mXyC/gateio.svg',
        verified: false,
        lastTickerCreatedAt: 1636633463000,
        numberOfMarkets: 1074,
        volume: 1996692863.3310318,
        websiteUrl: 'https://www.gate.io/signup/4296215',
        rank: 19,
        marketShare: 1.238497989276054,
      },
      {
        id: 555,
        uuid: 'Areyf_TNp',
        name: 'Nami',
        description: null,
        iconUrl: 'https://cdn.coinranking.com/6gnfOmI7J/nami-exchange.svg',
        verified: false,
        lastTickerCreatedAt: 1636633601000,
        numberOfMarkets: 417,
        volume: 1971174836.1312206,
        websiteUrl: 'https://nami.exchange/en',
        rank: 16,
        marketShare: 1.2226698036008001,
      },
      {
        id: 461,
        uuid: 'iuiDaBVcB',
        name: 'BeQuant',
        description: null,
        iconUrl: 'https://cdn.coinranking.com/LsQ1BxeiG/bq.png',
        verified: false,
        lastTickerCreatedAt: 1636633522000,
        numberOfMarkets: 124,
        volume: 1899988564.8303342,
        websiteUrl: 'https://bequant.io/',
        rank: 21,
        marketShare: 1.1785147632892294,
      },
      {
        id: 509,
        uuid: '3wgCrJww',
        name: 'AEX',
        description:
          'AEX is a global digital assets integrated service platform that intents to integrate information, community, application market and digital currency trading.',
        iconUrl: 'https://cdn.coinranking.com/Uj0OUvJzB/AEX.svg',
        verified: false,
        lastTickerCreatedAt: 1636633559000,
        numberOfMarkets: 307,
        volume: 1769002205.4849415,
        websiteUrl: 'https://www.aex.plus/#/',
        rank: 22,
        marketShare: 1.0972672436275315,
      },
      {
        id: 473,
        uuid: '8FXHCkosV',
        name: 'WhiteBIT',
        description:
          'WhiteBIT is a digital asset trading platform that focuses on security, liquidity, and execution speed - they want to attract beginners and professional traders at the same time.',
        iconUrl: 'https://cdn.coinranking.com/_dyCfkPR7/whitebit.svg',
        verified: false,
        lastTickerCreatedAt: 1636633529000,
        numberOfMarkets: 193,
        volume: 1684775941.935799,
        websiteUrl: 'https://whitebit.com/',
        rank: 23,
        marketShare: 1.0450238265424303,
      },
      {
        id: 296,
        uuid: 'X8P0C7SXai',
        name: 'BitMart',
        description:
          '<p><a href="https://www.bitmart.com/en?r=KDNaBQ" rel="nofollow noopener" target="_blank">BitMart Exchange</a> is a global digital assets trading platform with over 2.2 million users worldwide. The centralized exchange was launched in 2018 and is based in the Cayman Islands. It also has offices located in New York, China, Hong Kong, and Seoul.&nbsp;<a href="https://www.bitmart.com/en?r=KDNaBQ" rel="nofollow noopener" target="_blank">BitMart</a>&#39;s vision is &ldquo;to bring cryptocurrency available to everyone everywhere. They believe that the decentralized digital currency will reshape the global economy fundamentally, such financial freedom would bring further economic innovation, efficiency, and equality to the world.&rdquo; <a href="https://www.bitmart.com/en?r=KDNaBQ" rel="nofollow noopener" target="_blank">BitMart</a>&nbsp;says it won&rsquo;t happen unless they build simple, and secure products for individuals and institutions around the world to discover and interact with this new frontier. The exchange has three main priorities; being trustworthy, accessible, and professional. <a href="https://www.bitmart.com/en?r=KDNaBQ" rel="nofollow noopener" target="_blank">BitMart</a>&nbsp;supports spot trading, otc trading, and USD trading.</p>\n\n<p><a href="https://coinranking.com/coin/6uzcPMFgWUJNH+bitmarttoken-bmx" rel="nofollow noopener" target="_blank">BitMart token</a> (BMX) is the native token of the cryptocurrency exchange. BMX runs natively on the Ethereum blockchain. The BMX token has been established with a total supply of 1 billion. BitMart plans to use 20% of their profits each quarter to buy back and burn BMX until 50%&nbsp;of the total BMX supply is burned.</p>\n\n<p>&nbsp;</p>\n',
        iconUrl: 'https://cdn.coinranking.com/0KoAUbthl/bitmart.svg',
        verified: false,
        lastTickerCreatedAt: 1636633711000,
        numberOfMarkets: 403,
        volume: 1678714834.4941504,
        websiteUrl: 'https://www.bitmart.com/en?r=KDNaBQ',
        rank: 24,
        marketShare: 1.041264275177708,
      },
      {
        id: 333,
        uuid: 'viYPxjdOb',
        name: 'LBank',
        description:
          '<p><a href="https://www.lbex.pro/invite?icode=BJO2" rel="nofollow noopener" target="_blank">LBank</a> is a Hong-Kong centralized digital asset trading platform, focussing mainly on the Chinese market. The company was founded in October 2016. One of the co-founders is Eric He. LBank exchange doesn&rsquo;t offer fiat-to-crypto trading but allows to buy/sell crypto for CNY and USD via peer-to-peer OTC feature.</p>\n\n<h3>LBank safety</h3>\n\n<p><a href="https://www.lbex.pro/invite?icode=BJO2" rel="nofollow noopener" target="_blank">LBank</a> aims to provide professional asset management solutions and claims to have one of the highest staking rewards on any exchange. LBank offers hundreds of cryptocurrency trading pairs. The team aims to build the most professional integrated service platform for digital assets while ensuring security. LBank has had a lot of problems with the verification of information, such as information expiration, validity and stolen identities. Because of this matter, LBank had launched a new KYC strategy. If accounts have not passed the first round of verification, users will need to upload the relevant KYC information to be reviewed again.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/9BtVBP7RO/lbank.svg',
        verified: false,
        lastTickerCreatedAt: 1636633736000,
        numberOfMarkets: 194,
        volume: 1610382237.2206523,
        websiteUrl: 'https://www.lbex.pro/invite?icode=BJO2',
        rank: 25,
        marketShare: 0.9988792965565834,
      },
      {
        id: 358,
        uuid: 'Yvv0173EH',
        name: 'Simex',
        description: null,
        iconUrl: 'https://cdn.coinranking.com/EduMkLJAK/simex.svg',
        verified: false,
        lastTickerCreatedAt: 1636633461000,
        numberOfMarkets: 8,
        volume: 1210101014.463097,
        websiteUrl: 'https://simex.global',
        rank: 26,
        marketShare: 0.7505949967353532,
      },
      {
        id: 290,
        uuid: 'znlSM6AO_V',
        name: 'DigiFinex',
        description: null,
        iconUrl: 'https://cdn.coinranking.com/kwdSJ9LCV/digifinex.svg',
        verified: false,
        lastTickerCreatedAt: 1636633704000,
        numberOfMarkets: 272,
        volume: 1129828953.9233956,
        websiteUrl:
          'https://www.digifinex.com/en-ww/from/e1yDv3?channelCode=ljaUPp',
        rank: 27,
        marketShare: 0.700804271582156,
      },
      {
        id: 292,
        uuid: 'fud0hlTEC2',
        name: 'LATOKEN',
        description: null,
        iconUrl: 'https://cdn.coinranking.com/k6o_Wi3jY/latoken.svg',
        verified: false,
        lastTickerCreatedAt: 1636633712000,
        numberOfMarkets: 391,
        volume: 1108151897.5512223,
        websiteUrl: 'https://latoken.com/invite?r=cp52g3d9j9',
        rank: 28,
        marketShare: 0.6873585427856038,
      },
      {
        id: 335,
        uuid: 'YY5LBnZ-G',
        name: 'Bitforex',
        description:
          '<p><a href="https://www.bitforex.com/en/register?inviterId=2749737" rel="nofollow noopener" target="_blank">BitForex</a> is a digital asset cryptocurrency exchange that offers spot and perpetual futures contracts that can be traded with leverage up to 100x. It&rsquo;s a relatively new exchange that was launched in 2018. The exchange aims to provide a wide range of trading products, which includes spot trading, margin trading, and derivatives. According to its website, <a href="https://www.bitforex.com/en/register?inviterId=2749737" rel="nofollow noopener" target="_blank">BitForex</a> constantly launches new features and products to meet the user&#39;s needs.</p>\n\n<p>The exchange is supported in more than 180 countries and <a href="https://www.bitforex.com/en/register?inviterId=2749737" rel="nofollow noopener" target="_blank">offers over 300 trading pairs</a>.</p>\n\n<h2>BitForex Token (BF)</h2>\n\n<p><a href="https://coinranking.com/coin/2nh5ugplNocUp+bitforextoken-bf" rel="nofollow noopener" target="_blank">BitForex Token (BF)</a> is the native token of the BitForex ecosystem. As a holder of the coin you can enjoy several advantages; you get a trading bonus and may participate in BitForex global conferences and KOL meetings, and you may attend various events. BitForex token can also be used in new features, such as BitForex Insight and entertainments. And there are premium airdrops for premium BF holders.</p>\n\n<p>&nbsp;</p>\n',
        iconUrl: 'https://cdn.coinranking.com/GCbTzCvwV/bitforex.png',
        verified: false,
        lastTickerCreatedAt: 1636633736000,
        numberOfMarkets: 182,
        volume: 1091835462.4263527,
        websiteUrl: 'https://www.bitforex.com/en/register?inviterId=2749737',
        rank: 29,
        marketShare: 0.677237871516918,
      },
      {
        id: 510,
        uuid: 'ZYoDwKcX',
        name: 'dcoin',
        description:
          'Dcoin is a cryptocurrency exchange that wants to provide a secure, efficient and user oriented platform.',
        iconUrl: 'https://cdn.coinranking.com/bqNxLB8Tx/dcoin.svg',
        verified: false,
        lastTickerCreatedAt: 1636633569000,
        numberOfMarkets: 99,
        volume: 1041005534.3720669,
        websiteUrl: 'https://www.dcoin.com/',
        rank: 30,
        marketShare: 0.6457093551154235,
      },
      {
        id: 352,
        uuid: 'b_T97fQvy',
        name: 'Bitstamp',
        description:
          '<p>Bitstamp is a crypto exchange that wants to approach the industry in a mature way, and aims to provide reliable trading of cryptocurrencies.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/hZIwj0Exu/bitstamp.svg',
        verified: false,
        lastTickerCreatedAt: 1636633461000,
        numberOfMarkets: 120,
        volume: 941212712.4842196,
        websiteUrl: 'https://www.bitstamp.net/',
        rank: 31,
        marketShare: 0.5838103963310991,
      },
      {
        id: 465,
        uuid: 'SzBTouvLv',
        name: 'Bitvavo',
        description:
          '<p><a href="https://bitvavo.com/?a=C987B568C9" rel="nofollow noopener" target="_blank">Bitvavo</a> is a crypto exchange based in the Netherlands that supports many cryptocurrencies and also supports fiat deposits.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/nGJvYLWVE/bitvavo.png',
        verified: false,
        lastTickerCreatedAt: 1636633524000,
        numberOfMarkets: 156,
        volume: 764951867.1081257,
        websiteUrl: 'https://bitvavo.com/?a=C987B568C9',
        rank: 33,
        marketShare: 0.47448026018677103,
      },
      {
        id: 315,
        uuid: 'YcZbQQOtnIM',
        name: 'DragonEx',
        description: null,
        iconUrl: 'https://cdn.coinranking.com/MFQcpDOqw/dragonex.svg',
        verified: false,
        lastTickerCreatedAt: 1636633714000,
        numberOfMarkets: 124,
        volume: 740877728.6545331,
        websiteUrl:
          'https://dragonex.io/en-us/account/register?inviteId=1407495',
        rank: 32,
        marketShare: 0.4595476821143545,
      },
      {
        id: 519,
        uuid: '6v5PtWJj',
        name: 'GMO Japan',
        description: null,
        iconUrl: 'https://cdn.coinranking.com/B5lxmHJV5/gmo-japan.svg',
        verified: false,
        lastTickerCreatedAt: 1636633569000,
        numberOfMarkets: 5,
        volume: 738693219.3493962,
        websiteUrl: 'https://coin.z.com/jp/',
        rank: 34,
        marketShare: 0.4581926863452739,
      },
      {
        id: 332,
        uuid: 'GbQYdtzPg',
        name: 'Bibox',
        description: null,
        iconUrl: 'https://cdn.coinranking.com/iAb5fjrVQ/bix.svg',
        verified: false,
        lastTickerCreatedAt: 1636633736000,
        numberOfMarkets: 173,
        volume: 711689193.1012183,
        websiteUrl: 'https://www.bibox.com/',
        rank: 35,
        marketShare: 0.4414427731137859,
      },
      {
        id: 549,
        uuid: 'OL8D20aT',
        name: 'PrimeBit',
        description:
          'PrimeBit is a peer-to-peer cryptocurrency exchange platform, where you can trade perpetual contracts (with no limit to your profit) with Fair Price marking and up to 200x leverage.',
        iconUrl: 'https://cdn.coinranking.com/KkSm6S90g/primebit.svg',
        verified: false,
        lastTickerCreatedAt: 1636633594000,
        numberOfMarkets: 6,
        volume: 636948830.1607795,
        websiteUrl:
          'https://primebit.com/n/l18_18346?promo_code=START10&uni_afi_username=CoinRanking',
        rank: 36,
        marketShare: 0.39508321981470174,
      },
      {
        id: 609,
        uuid: 'uaMqYJoJM',
        name: 'SushiSwap',
        description: null,
        iconUrl: 'https://cdn.coinranking.com/t4AbSi1OR/sushiswap.png',
        verified: false,
        lastTickerCreatedAt: 1636633655000,
        numberOfMarkets: 132,
        volume: 583288037.2960731,
        websiteUrl: 'https://exchange.sushiswapclassic.org',
        rank: 37,
        marketShare: 0.3617987897020873,
      },
      {
        id: 338,
        uuid: '0wi86tE-f',
        name: 'CoinTiger',
        description:
          '<p>&nbsp;</p>\n\n<p><a href="https://www.cointiger.top/#/register?refCode=UU082o" rel="nofollow noopener" target="_blank">CoinTiger exchange</a> is a global cryptocurrency trading platform, which is co-founded by SINGAPORE TAI-E CYBER-TECH PTE. The platform provides trading of several coins, such as BTC, ETH, LTC, and EOS. They have more than 300 trading pairs available.&nbsp;</p>\n\n<p>The centralized exchange was launched in 2017 and is based in Singapore. <a href="https://www.cointiger.top/#/register?refCode=UU082o" rel="nofollow noopener" target="_blank">CoinTiger</a> offers CNY/USD cash withdrawal services and multi-language customer service which is available 24/7, according to the website of the platform. <a href="https://www.cointiger.top/#/register?refCode=UU082o" rel="nofollow noopener" target="_blank">CoinTiger</a> also aims to offer a secure platform, by multiple verifications at login. The exchange claims to cooperate with multiple security institutions.</p>\n\n<h2>TigerCash (TCH)</h2>\n\n<p><a href="https://coinranking.com/coin/6hIn06L2+tigercash-tch" rel="nofollow noopener" target="_blank">TigerCash (TCH)</a> is the platform token issued on Ethereum by the <a href="https://www.cointiger.top/#/register?refCode=UU082o" rel="nofollow noopener" target="_blank">CoinTiger exchange</a>. The coin was officially launched in 2017, with a total supply of 1.05 billion and 672 million in circulation. Since its launch, 50 million TCH have been bought back from the secondary market and burned. Currently, there is a total supply of 1 billion TCH.</p>\n\n<p>&nbsp;</p>\n',
        iconUrl: 'https://cdn.coinranking.com/82VCN6DET/cointiger.svg',
        verified: false,
        lastTickerCreatedAt: 1636633736000,
        numberOfMarkets: 257,
        volume: 555144128.7892243,
        websiteUrl: 'https://www.cointiger.top/#/register?refCode=UU082o',
        rank: 38,
        marketShare: 0.34434183638882115,
      },
      {
        id: 588,
        uuid: 'bkPJvKJ7a',
        name: 'Bithumb Global',
        description:
          '<p><a href="https://www.bithumb.pro/register;i=dkxsat" rel="nofollow noopener" target="_blank">Bithumb Global</a> is a worldwide trading platform for digital assets. It is a global product initiated by Bithumb Korea, which is one of the largest South Korean cryptocurrency exchanges.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/HJC5VoKWl/Bithumb.svg',
        verified: false,
        lastTickerCreatedAt: 1636633637000,
        numberOfMarkets: 203,
        volume: 491419129.76923215,
        websiteUrl: 'https://www.bithumb.pro/register;i=dkxsat',
        rank: 39,
        marketShare: 0.30481483421322714,
      },
      {
        id: 494,
        uuid: 'rvyJU4ce',
        name: 'ExMarkets',
        description:
          '<p>ExMarkets is a digital asset exchange platform powered by the state-of-the-art trading engine developed in-house. On the exchange, ExMarkets users can trade cryptocurrencies as well as gain the chance to participate in the token sales of the most promising blockchain and crypto projects through ExMarkets Initial Exchange Offering (IEO) LaunchPad. ExMarkets has been operating in the crypto market since the autumn of 2018 and has so far gathered a 160,000 member community that is actively trading on the platform on a daily basis. ExMarkets has hosted more than 60 Initial Exchange Offerings, and generates around $30,000 daily trading volume.</p>\n<h3>Trading on ExMarkets</h3>\n<p>It takes only a few minutes to set up your account and users are allowed to make deposits in Bitcoin, Ethereum, other supported cryptocurrencies without paying any deposit or withdrawal fees.</p>',
        iconUrl: 'https://cdn.coinranking.com/rhDZXgGuA/exmarkets.svg',
        verified: false,
        lastTickerCreatedAt: 1636633548000,
        numberOfMarkets: 88,
        volume: 448357183.4762577,
        websiteUrl: 'https://exmarkets.com/home/ref/5LFGLI5Z43',
        rank: 40,
        marketShare: 0.27810460006675475,
      },
      {
        id: 611,
        uuid: 'vzKEiB3Sk1',
        name: 'Uniswap v2',
        description:
          '<p>Uniswap is an automated liquidity protocol; it allows anyone with an Ethereum wallet to exchange tokens without the involvement of any central party. The Uniswap protocol was created by Hayden Adams in 2018.&nbsp;</p>\n\n<p>There is no order book or any centralized party needed to make trades. Uniswap works with a model that involves liquidity providers creating liquidity pools. Any ERC-20 token can be launched as long as there is a liquidity pool available for traders.</p>\n\n<h2>Uniswap token&nbsp;(UNI)</h2>\n\n<p><a href="https://coinranking.com/coin/_H5FVG9iW+uniswap-uni" rel="nofollow noopener" target="_blank">Uniswap (UNI)</a> is the native token of the Uniswap protocol, and&nbsp;provides its holders with governance rights; UNI holders can vote on changes to the protocol. 1 billion UNI tokens have been minted at the beginning. 60% of those are distributed to existing Uniswap community members, and the other 40% will be made available to team members, investors, and advisors. Community members are the Ethereum addresses that have interacted with&nbsp;Uniswap.</p>\n\n<p>&nbsp;</p>\n',
        iconUrl: 'https://cdn.coinranking.com/1heSvUgtl/uniswap-v2.svg',
        verified: false,
        lastTickerCreatedAt: 1636633683000,
        numberOfMarkets: 657,
        volume: 446394504.1846813,
        websiteUrl: 'https://uniswap.org/',
        rank: 41,
        marketShare: 0.2768871998341742,
      },
      {
        id: 368,
        uuid: 'g4KrbpvBGZ',
        name: 'Gemini',
        description:
          '<p>Gemini, located in the United States, is a cryptocurrency exchange launched in 2015. Gemini is currently a trust company that is regulated by the New York State Department of Financial Services.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/WZWRrgFmC/gemini.svg',
        verified: false,
        lastTickerCreatedAt: 1636633486000,
        numberOfMarkets: 54,
        volume: 445810914.40674716,
        websiteUrl: 'https://gemini.com/',
        rank: 42,
        marketShare: 0.2765252138824001,
      },
      {
        id: 506,
        uuid: '4rcgHqoYl',
        name: 'TOKOK',
        description:
          '<p><a href="https://www.tokok.com/reg?code=WNQEOXWZ" rel="nofollow noopener" target="_blank">TOKOK</a> is a digital asset exchange that operates globally. The platform has also issued its own loyalty token to incentivize trading activity.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/45ULOuMmM/TOKOK.svg',
        verified: false,
        lastTickerCreatedAt: 1636633555000,
        numberOfMarkets: 118,
        volume: 400485219.5179908,
        websiteUrl: 'https://www.tokok.com/reg?code=WNQEOXWZ',
        rank: 45,
        marketShare: 0.24841083384269042,
      },
      {
        id: 647,
        uuid: 'FeCJqGOi1',
        name: 'Uniswap v3',
        description: null,
        iconUrl: 'https://cdn.coinranking.com/0ydQxoIvK/uniswap-v3.png',
        verified: false,
        lastTickerCreatedAt: 1636633688000,
        numberOfMarkets: 220,
        volume: 353050652.4488489,
        websiteUrl: 'https://info.uniswap.org/',
        rank: 47,
        marketShare: 0.21898837382582775,
      },
      {
        id: 340,
        uuid: 'I0AFppISB',
        name: 'Poloniex',
        description:
          '<p>Poloniex, founded in 2014, is a crypto exchange thats wants to give traders and hodlers a safe place to trade and store cryptocurrencies.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/-AJNsnZh2/poloniex.svg',
        verified: false,
        lastTickerCreatedAt: 1636633461000,
        numberOfMarkets: 276,
        volume: 322261773.3871864,
        websiteUrl: 'https://poloniex.com/',
        rank: 48,
        marketShare: 0.1998908122978529,
      },
      {
        id: 342,
        uuid: 'UJpQQ94PU',
        name: 'Liquid',
        description:
          '<p><a href="https://www.liquid.com/sign-up/?affiliate=M4UonOEI896677" rel="nofollow noopener" target="_blank">Liquid</a> is a cryptocurrency exchange that tries to bridge the gap between fiat currency and cryptocurrency.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/2UTOQpv2w/liquid.svg',
        verified: false,
        lastTickerCreatedAt: 1636633456000,
        numberOfMarkets: 196,
        volume: 321262552.40312284,
        websiteUrl: 'https://www.liquid.com/sign-up/?affiliate=M4UonOEI896677',
        rank: 49,
        marketShare: 0.19927102084052248,
      },
      {
        id: 307,
        uuid: 'LRey_PE4Bg9',
        name: 'FINEXBOX',
        description: null,
        iconUrl: 'https://cdn.coinranking.com/cE-4BTsBf/finexbox.svg',
        verified: false,
        lastTickerCreatedAt: 1636633714000,
        numberOfMarkets: 307,
        volume: 293223070.63976556,
        websiteUrl:
          'https://www.finexbox.com/Reg/register/referrer/568120.html',
        rank: 50,
        marketShare: 0.18187884079019334,
      },
      {
        id: 347,
        uuid: 'L3Hv_wCiv',
        name: 'ABCC',
        description: null,
        iconUrl: 'https://cdn.coinranking.com/fdR55pNf3/abcc.svg',
        verified: false,
        lastTickerCreatedAt: 1636633461000,
        numberOfMarkets: 53,
        volume: 290704922.52318716,
        websiteUrl: 'https://abcc.com/at_invitation/share?aff=66dc59',
        rank: 51,
        marketShare: 0.1803168973203906,
      },
      {
        id: 407,
        uuid: 'FRrDoGh7ff',
        name: 'CoinEx',
        description:
          '<p><a href="https://www.coinex.com/register?refer_code=8b5nc" rel="nofollow noopener" target="_blank">CoinEx</a> is a global and centralized cryptocurrency trading platform, founded in 2017 and based in Hong Kong. The exchange aims to put the user first, by providing&nbsp;24/7 exchange services, multilingual support, community backup, and professional customer service. <a href="https://www.coinex.com/register?refer_code=8b5nc" rel="nofollow noopener" target="_blank">CoinEx</a> supports multiple languages like Chinese, English, Japanese, Korean, Russian, and provides global <a href="https://www.coinex.com/register?refer_code=8b5nc" rel="nofollow noopener" target="_blank">trading services</a> in over 100 countries/regions. <a href="https://www.coinex.com/register?refer_code=8b5nc" rel="nofollow noopener" target="_blank">CoinEx</a> focuses on being secure, stable, professional, and compliant.</p>\n\n<h2>CoinEx token (CET)</h2>\n\n<p><a href="https://coinranking.com/coin/APDVU0XEViZ2o+coinextoken-cet" rel="nofollow noopener" target="_blank">CoinEx Token (CET)</a> is the native token for the <a href="https://www.coinex.com/register?refer_code=8b5nc" rel="nofollow noopener" target="_blank">CoinEx exchange</a> and ecosystem. CET is issued on Ethereum and circulated via airdrop incentives, transaction fee discounts, promotions, and team unlocking. CoinEx claims to repurchase and burn CET every day with 50% of its transaction fee income, and burn all the CET repurchased monthly at the end of each month until the total supply of CET reduces to 3 billion. In March 2021, when the 3 billion target was achieved, CoinEx made the decision to use 20% of its fee income for CET repurchase and burning until CET is completely burned.</p>\n\n<p>&nbsp;</p>\n',
        iconUrl: 'https://cdn.coinranking.com/cyoUeU2Ws/CoinExLogo.svg',
        verified: false,
        lastTickerCreatedAt: 1636633492000,
        numberOfMarkets: 568,
        volume: 286699872.7151658,
        websiteUrl: 'https://www.coinex.com/register?refer_code=8b5nc',
        rank: 52,
        marketShare: 0.1778326664077254,
      },
      {
        id: 326,
        uuid: 'WHQEh9RmN',
        name: 'Bittrex',
        description:
          '<p>Bittrex is a US-based global cryptocurrency exchange that started in 2013.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/sndyHcp6P/bittrex.svg',
        verified: false,
        lastTickerCreatedAt: 1636633489000,
        numberOfMarkets: 738,
        volume: 282458612.202515,
        websiteUrl: 'https://bittrex.com',
        rank: 53,
        marketShare: 0.17520191998027998,
      },
      {
        id: 391,
        uuid: 'VxDO6Iucon',
        name: 'Coincheck',
        description: null,
        iconUrl: 'https://cdn.coinranking.com/koWAZH3Uo/coincheck.svg',
        verified: false,
        lastTickerCreatedAt: 1636633488000,
        numberOfMarkets: 1,
        volume: 267308162.61203676,
        websiteUrl: 'https://coincheck.com/',
        rank: 54,
        marketShare: 0.1658044799938755,
      },
      {
        id: 350,
        uuid: '8t10ctWCU',
        name: 'BitFlyer',
        description:
          '<p>BitFlyer, founded in 2014, is a Japan-based cryptocurrency exchange where users can buy, sell and trade digital currencies.</p>\n',
        iconUrl: 'https://cdn.coinranking.com/iGTwIBIAF/bitflyer.svg',
        verified: false,
        lastTickerCreatedAt: 1636633737000,
        numberOfMarkets: 3,
        volume: 261129841.52051598,
        websiteUrl: 'https://bitflyer.com',
        rank: 55,
        marketShare: 0.16197222397219324,
      },
    ],
  },
};

const Exchanges = () => {
  // const { data, isFetching } = useGetExchangesQuery();

  // if (isFetching) return <Spinner />;

  return (
    <>
      <Row>
        <Col span={6}>Exchanges</Col>
        <Col span={6}>24h Trade Volume</Col>
        <Col span={6}>Markets</Col>
        <Col span={6}>Change</Col>
      </Row>
      <Row>
        {data?.data?.exchanges.map(exchange => (
          <Col span={24}>
            <Collapse>
              <Panel
                key={exchange.id}
                showArrow={false}
                header={
                  <Row key={exchange.id}>
                    <Col span={6}>
                      <Text>
                        <strong>{exchange.rank}.</strong>
                      </Text>
                      <Avatar
                        className='exchange-image'
                        src={exchange.iconUrl}
                      />
                      <Text>
                        <strong>{exchange.name}</strong>
                      </Text>
                    </Col>
                    <Col span={6}>${millify(exchange.volume)}</Col>
                    <Col span={6}>{millify(exchange.numberOfMarkets)}</Col>
                    <Col span={6}>{millify(exchange.marketShare)}%</Col>
                  </Row>
                }
              >
                {/* {HTMLReactParser(exchange.description || '')} */}
              </Panel>
            </Collapse>
          </Col>
        ))}
      </Row>
    </>
  );
};

export default Exchanges;
